################################################################################
# Colors and Styles
################################################################################
colors:
  annual_activities:
    critical_period: "#7b3294"     # Deep purple – stands apart, academic/annual theme
    data: "#000000"                
    forecast: "#3498DB"            
    communication: "#27AE60"        

  snow_forecasting:
    critical_period: "#2166ac"     # Deep blue – cold/snow association
    data: "#000000"           
    forecast: "#377eb8"              
    communication: "#4daf4a" 

  hydrological_forecasting:
    critical_period: "#b2182b"     # Deep red – strong, water/emergency association
    data: "#000000"                 
    forecast: "#377eb8"              
    communication: "#4daf4a"         

  river_ice_monitoring:
    critical_period: "#fc8d59"     # Coral orange – freeze/thaw, distinct but warm
    data: "#000000"           
    forecast: "#377eb8"              
    communication: "#4daf4a" 

  planning_and_improvement:
    critical_period: "#6B8E23"     # Olive green – institutional/structural, not hazard-colored
    admin: "#666666"                 
    capacity: "#666666"              
    block: "#000000"                


  visualization:
    snow_survey: "#e41a1c"          # Bright red – survey highlight
    snow_bulletin: "#4daf4a"        # Green
    spring_breakup_outlook: "#4daf4a"
    streamflow: "#67001f"           # Very deep red – serious emphasis
    swe: "#053061"                  # Very deep blue – SWE emphasis


styles:
  # Line Styles
  solid:
    linestyle: "-"
    linewidth: 3

  dashed:
    linestyle: "--"
    linewidth: 3

  dotted:
    linestyle: ":"
    linewidth: 3

  dashdot:
    linestyle: "-."
    linewidth: 3

  # Marker Styles
  downward_triangle:
    marker: "v"
    markersize: 10
    markeredgewidth: 2
    markerfacecolor: "visualization.snow_survey"  # Reference to color

  diamond:
    marker: "P"
    markersize: 10
    markeredgewidth: 2
    markerfacecolor: "visualization.snow_bulletin"  # Reference to color

month_ranges:
  Jan: [1, 31]
  Feb: [32, 59]
  Mar: [60, 90]
  Apr: [91, 120]
  May: [121, 151]
  Jun: [152, 181]
  Jul: [182, 212]
  Aug: [213, 243]
  Sep: [244, 273]
  Oct: [274, 304]
  Nov: [305, 334]
  Dec: [335, 365]

sectors:
  Jan: 1
  Feb: 1
  Mar: 1
  Apr: 1
  May: 1
  Jun: 1
  Jul: 1
  Aug: 1
  Sep: 1
  Oct: 1
  Nov: 1
  Dec: 1

################################################################################
# Track Configs
################################################################################
track_configs:

  #################################################################################
  # Snow Seasonal Forecasting
  #################################################################################
  snow_based_seasonal_forecasts_critical:
    type: "infill"
    color: "snow_forecasting.critical_period"
    alpha: 0.5
    r_start: 84
    r_end: 100
    months: ["Mar", "Apr", "May"]
  snow_based_seasonal_forecasts_total:
    type: "infill"
    color: "snow_forecasting.critical_period"
    alpha: 0.2
    r_start: 84
    r_end: 100
    months: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aug"]

  snow_based_flood_risk_forecasts:
    type: "line"
    color: "snow_forecasting.forecast"
    linestyle: "--"
    linewidth: 5
    r_start: 93
    r_end: 95
    months: ["Mar", "Apr"]

  snow_based_forecast_1:
    type: "line"
    color: "snow_forecasting.forecast"
    linestyle: "-"
    linewidth: 3
    r_start: 91
    r_end: 93
    months: ["Mar", "Apr", "May", "Jun", "Jul","Aug"]

  snow_based_forecast_2:
    type: "line"
    color: "snow_forecasting.forecast"
    linestyle: "-"
    linewidth: 3
    r_start: 89
    r_end: 91
    months: ["Apr", "May", "Jun", "Jul","Aug"]

  snow_based_forecast_3:
    type: "line"
    color: "snow_forecasting.forecast"
    linestyle: "-"
    linewidth: 3
    r_start: 87
    r_end: 89
    months: ["May", "Jun", "Jul","Aug"]

  automated_station_data:
    type: "line"
    color: "snow_forecasting.data"
    linestyle: "-"
    linewidth: 3
    r_start: 97
    r_end: 99
    months: ["Nov","Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aug"]

  large_domain_snow_products:
    type: "line"
    color: "snow_forecasting.data"
    linestyle: ":"
    linewidth: 3
    r_start: 95
    r_end: 97
    months: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aug"]
  
  snow_flood_risk_communication:
    type: "line"
    color: "snow_forecasting.communication"
    linestyle: "dotted"
    linewidth: 3
    r_start: 85
    r_end: 87
    months: ["Dec","Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul","Aug"]

  snow_surveys:
    type: "marker"
    color: "visualization.snow_survey"
    marker: "v"
    markersize: 10
    linewidth: 3
    months: ["Feb", "Mar", "Apr"]
    r_points:
      Feb: 91
      Mar: 89
      Apr: 87
    position: 21

  snow_bulletin:
    type: "marker"
    color: "visualization.snow_bulletin"
    marker: "P"
    markersize: 10
    linewidth: 3
    months: ["Mar", "Apr", "May"]
    r_points:
      Mar: 85
      Apr: 85
      May: 85
    position: 7

  hydrological_critical_period:
    type: "infill"
    color: "hydrological_forecasting.critical_period"
    alpha: 0.7
    r_start: 70
    r_end: 83
    months: ["May", "Jun", "Jul"]
  
  hydrological_total:
    type: "infill"
    color: "hydrological_forecasting.critical_period"
    alpha: 0.2
    r_start: 70
    r_end: 83
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  hydrometric_observations:
    type: "line"
    color: "hydrological_forecasting.data"
    linestyle: "-"
    linewidth: 3
    r_start: 81
    r_end: 81
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]
  
  nwp_forecasts:
    type: "line"
    color: "hydrological_forecasting.data"
    linestyle: "dashed"
    linewidth: 3
    r_start: 79
    r_end: 79
    months: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  hydrologic_short_term_forecasts:
    type: "line"
    color: "hydrological_forecasting.forecast"
    linestyle: "-"
    linewidth: 3
    r_start: 77
    r_end: 77
    months: [ "May", "Jun", "Jul", "Aug", "Sep", "Oct"]

  hydrologic_flood_altas_portal:
    type: "line"
    color: "hydrological_forecasting.communication"
    linestyle: "dashdot"
    linewidth: 3 
    r_start: 75
    r_end: 75
    months: ["Oct", "Nov", "Dec", "Jan","Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  hydrologic_communication_calls:
    type: "line"
    color: "hydrological_forecasting.communication"
    linestyle: "dotted"
    linewidth: 3
    r_start: 73
    r_end: 73
    months: ["Apr", "May", "Jun", "Jul", "Aug"]

  hydrologic_weekly_communication_calls:
    type: "line"
    color: "hydrological_forecasting.communication"
    linestyle: "dashed"
    linewidth: 3
    r_start: 71
    r_end: 71
    months: ["Oct", "Nov", "Dec", "Jan","Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"]

  river_ice_monitoring:
    type: "infill"
    color: "river_ice_monitoring.critical_period"
    linestyle: "-"
    alpha: 0.5
    linewidth: 3
    r_start: 55
    r_end: 69
    months: ["Oct", "Nov", "Dec", "Apr", "May"]

  river_ice_meteo_hydro:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "-"
    linewidth: 3
    r_start: 67
    r_end: 67
    months: ["Oct", "Nov", "Dec", "Apr", "May"]

  remote_sensing_river_ice:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "dashed"
    linewidth: 3
    r_start: 65
    r_end: 65
    months: ["Oct", "Nov", "Dec", "Apr", "May"]

  airborne_observations:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "dotted"
    linewidth: 3
    r_start: 63
    r_end: 63
    months: ["Apr", "May"]

  citizen_observations:
    type: "line"
    color: "river_ice_monitoring.data"
    linestyle: "dashdot"
    linewidth: 3
    r_start: 61
    r_end: 61
    months: ["Apr", "May"]

  river_ice_flood_altas:
    type: "line"
    color: "river_ice_monitoring.communication"
    linestyle: "dashdot"
    linewidth: 3
    r_start: 59
    r_end: 59
    months: ["Apr", "May", "Oct", "Nov", "Dec"]
  
  river_ice_monitoring_communication:
    type: "line"
    color: "river_ice_monitoring.communication"
    linestyle: "dotted"
    linewidth: 3
    r_start: 57
    r_end: 57
    months: ["Apr", "May", "Oct", "Nov", "Dec"]


  #################################################################################
  # Planning and Improvement
  #################################################################################
  planning_and_improvement_critical:
    type: "infill"
    color: "planning_and_improvement.critical_period"
    alpha: 0.5
    linewidth: 3
    r_start: 45
    r_end: 54
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb", "Mar"]
  planning_and_improvement_reporting:
    type: "line"
    color: "planning_and_improvement.admin"
    linestyle: "dashed"
    linewidth: 3
    r_start: 52
    r_end: 52
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb"]

  planning_and_improvement_documentation:
    type: "line"
    color: "planning_and_improvement.admin"
    linestyle: "dotted"
    linewidth: 3
    r_start: 50
    r_end: 50
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb"]

  planning_and_improvement_process_improvement:
    type: "line"
    color: "planning_and_improvement.capacity"
    linestyle: "dashdot"
    linewidth: 5
    r_start: 48
    r_end: 48
    months: ["Sep","Oct", "Nov", "Dec", "Jan", "Feb"]

  planning_and_improvement_no_modifications:
    type: "line"
    color: "planning_and_improvement.block"
    linestyle:  "dashdot"
    linewidth: 5
    r_start: 46
    r_end: 46
    months: ["Mar"]

  # #################################################################################
  # # Data Plot Tracks for Streamflow and SWE
  # #################################################################################
  streamflow_data:
    type: "data_plot"
    data_type: "streamflow"
    color_mean: "visualization.streamflow"
    color_envelope: "visualization.streamflow"
    date_col: "Date"
    value_col: "discharge_cms"
    r_start: 24
    r_end: 36
    months: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

  swe_data:
    type: "data_plot"
    data_type: "swe"
    color_mean: "visualization.swe"
    color_envelope: "visualization.swe"
    r_start: 36
    r_end: 45
    months: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

################################################################################
# Plot Settings
################################################################################
plot_settings:
  figsize:
    plot: [30, 24]  # Increased height to accommodate larger circle
  titles:
    plot: "Decision Calendars for the Yukon River at Ross River"
  legend:
    loc: "upper center"  # Changed to bottom center alignment
    bbox: [0.5, -0.1]  # Moved legend closer to plot
    fontsize: 28        # Slightly smaller for more compact layout
    title_fontsize: 28
    borderpad: 1.5
    labelspacing: 1.0
    columnspacing: 2.0  # Space between columns
    ncol: 4            # Four columns for better distribution
    facecolor: "white"
    edgecolor: "black"


################################################################################
# LegendSettings
################################################################################
legend_groups:
  Snow_Seasonal_Forecasting:
    color: "snow_forecasting.critical_period"
    elements:
      - type: line
        color: "snow_forecasting.data"
        linestyle: "-"
        linewidth: 3
        label: "Meteo and Hydro Stations"
      - type: line
        color: "snow_forecasting.data"
        linestyle: ":"
        linewidth: 3
        label: "Large Domain Snow Products"
      - type: marker
        color: "visualization.snow_survey"
        marker: "v"
        markersize: 10
        linewidth: 3
        label: "Snow Surveys"
      - type: line
        color: "snow_forecasting.forecast"
        linestyle: "dashed"
        linewidth: 5
        label: "Flood Risk Assessment"
      - type: line
        color: "snow_forecasting.forecast"
        linestyle: "-"
        linewidth: 3
        label: "Snow Based Forecasts"
      - type: line
        color: "snow_forecasting.communication"
        linestyle: "dotted"
        linewidth: 3
        label: "Snow Flood Risk Communication"
      - type: marker
        color: "visualization.snow_bulletin"
        marker: "P"
        markersize: 10
        linewidth: 3
        label: "Snow Bulletin"
      - type: space


  Hydro_Shortterm_Outlook:
    color: "hydrological_forecasting.critical_period"
    elements:
      - type: line
        color: "hydrological_forecasting.data"
        linestyle: "-"
        linewidth: 3
        label: "Meteo and Hydro Stations"
      - type: line
        color: "hydrological_forecasting.data"
        linestyle: "dashed"
        linewidth: 3
        label: "NWP Forecasts"
      - type: line
        color: "hydrological_forecasting.forecast"
        linestyle: "-"
        linewidth: 3
        label: "Model Based Forecasts (MESH, BC CLEVER, etc.)"
      - type: line
        color: "hydrological_forecasting.communication"
        linestyle: "dashdot"
        linewidth: 3
        label: "Flood Altas Portal"
      - type: line
        color: "hydrological_forecasting.communication"
        linestyle: "dotted"
        linewidth: 3
        label: "Event Based Communication"
      - type: line
        color: "hydrological_forecasting.communication"
        linestyle: "dashed"
        linewidth: 3
        label: "Emergency Management Calls"
      - type: space


  River_Ice_Monitoring:
    color: "river_ice_monitoring.critical_period"
    elements:
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "-"
        linewidth: 3
        label: "Meteo and Hydro Stations"
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "dashed"
        linewidth: 3
        label: "Remote Sensing"
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "dotted"
        linewidth: 3
        label: "Airborne Observations"
      - type: line
        color: "river_ice_monitoring.data"
        linestyle: "dashdot"
        linewidth: 3
        label: "Citizen Observations"
      - type: line
        color: "river_ice_monitoring.communication"
        linestyle: "dashdot"
        linewidth: 3
        label: "Flood Altas Portal"
      - type: line
        color: "river_ice_monitoring.communication"
        linestyle: "dotted"
        linewidth: 3
        label: "Event Based Communication"
      - type: space

  Planning_and_Improvement:
    color: "planning_and_improvement.critical_period"
    elements:
      - type: line
        color: "planning_and_improvement.admin"
        linestyle: "dashed"
        linewidth: 3
        label: "Reporting on Hydrometric Data"
      - type: line
        color: "planning_and_improvement.admin"
        linestyle: "dotted"
        linewidth: 3
        label: "Document Breakup + Community Information"
      - type: line
        color: "planning_and_improvement.capacity"
        linestyle: "dashdot"
        linewidth: 5
        label: "Capacity for Process Improvement"
      - type: line
        color: "planning_and_improvement.block"
        linestyle: "dashdot"
        linewidth: 5
        label: "No Upgrades Ahead of Operations"
      - type: space

  SWE_Annual_Range:
    description: "Seasonal Data"
    color: "visualization.swe"
    elements:
      - type: space

  Streamflow_Annual_Range:
    description: "Streamflow Data"
    color: "visualization.streamflow"
    elements:
      - type: space